### ISSUE TITLE
issues with cont-init.d and services.d scripts from v2 to v3

### ISSUE THREAD

**Issue by abesnier** [just-containers/s6-overlay#382] opened 2022-01-26 16:44 UTC
Hello, 

This is more an issue with me than with s6 overlay, but I could not find another place to ask my questions.

I am trying to update an image that currently uses v2.2.0.3 and move it to v3.0.0.0-1.
I have updated the Dockerfile, archives are properly downloaded and extracted. I have included the symlinks archives, as mentionned in the readme and https://github.com/just-containers/s6-overlay/issues/376. The image builds without issues.
I made sure the scripts are executable, and I have tried different shebangs (`#!/usr/bin/env`, `#!/usr/bin/with-contenv`, `#!/command/with-contenv`), and whatever I do, when I run the container (docker run etc...), I get an error message in the logs (docker logs):
`s6-applyuidgid: fatal: unable to exec <the service I want to start>: No such file or directory`

However, if I run the same scripts from inside the container directly (docker exec -it mycontainer bash), they would run as expected.

The scripts are not terribly complex, and consist in only one instruction per service (for a grand total of 2...):
```
#theshebang sh

echo "Starting up <service>"
s6-setuidgid <user> <service>
```

Obviously, I am missing something in the environment variables, but I cannot figure what.

And please indicate me if there is another option to ask questions (forum, reddit, whatever...)

**Comment by skarnet** [comment] 2022-01-26 19:18
- Does it work (as in, your service is found, even if it fails later on) when you simply use `#!/bin/sh` as your shebang?
  - If it doesn't, is your service located in `/usr/sbin` or something similar? in that case, either use the full path to your service, or modify your script so it changes PATH to include the path to your service. The default PATH is `/command:/bin:/usr/bin`.
  - If it does: yeah it has been reported and I believe it is due to `with-contenv` also replacing PATH with its value *in the host*, which is incorrect even when you want the container environment; I will fix that.
- minor point, but still worth mentioning: if your interpreter is a shell, you should `exec` the last line, so the shell is replaced with your service instead of staying around.

**Comment by skarnet** [comment] 2022-01-26 19:32
(Tentative fix pushed to git; next release will include it.)

**Comment by colinmollenhour** [comment] 2022-01-27 00:33
New user here, just spent several hours trying to figure out why I couldn't get this to work. It seems 3.0.0.0-1 is quite broken, when will the next release be?

You might consider some more robust tests as part of the release process. Here is a simple example that demonstrates the error I ran into which is just the basic way it is expected to work according to the README:

```
FROM ubuntu
ARG S6_OVERLAY_VERSION=3.0.0.0-1

RUN apt-get update && apt-get install -y nginx xz-utils
RUN echo "daemon off;" >> /etc/nginx/nginx.conf
#CMD ["/usr/sbin/nginx"]

ADD https://github.com/just-containers/s6-overlay/releases/download/v${S6_OVERLAY_VERSION}/s6-overlay-noarch-${S6_OVERLAY_VERSION}.tar.xz /tmp
RUN tar -C / -Jxpf /tmp/s6-overlay-noarch-${S6_OVERLAY_VERSION}.tar.xz
ADD https://github.com/just-containers/s6-overlay/releases/download/v${S6_OVERLAY_VERSION}/s6-overlay-x86_64-${S6_OVERLAY_VERSION}.tar.xz /tmp
RUN tar -C / -Jxpf /tmp/s6-overlay-x86_64-${S6_OVERLAY_VERSION}.tar.xz

RUN mkdir -p /etc/s6-overlay/s6-rc.d/nginx /etc/cont-init.d/ \
  && echo '#!/usr/bin/with-contenv sh\necho "Starting $FOO..."\nexec /usr/sbin/nginx' > /etc/s6-overlay/s6-rc.d/nginx/run \
  && echo "longrun" > /etc/s6-overlay/s6-rc.d/nginx/type \
  && touch /etc/s6-overlay/s6-rc.d/user/contents.d/nginx \
  && echo '#!/usr/bin/with-contenv sh\necho "Hello $FOO"' > /etc/cont-init.d/00-hello \
  && chmod +x /etc/cont-init.d/00-hello

ENV FOO=bar
ENTRYPOINT ["/init"]
CMD []
```

```
docker build . -t s6demo
docker run --rm --name s6demo -p 80:80 s6demo
```

**Comment by skarnet** [comment] 2022-01-27 01:44
@colinmollenhour It seems that you missed the [part of the README](https://github.com/just-containers/s6-overlay/blob/master/README.md#installation) that says:

3. `s6-overlay-symlinks-noarch-3.0.0.0.tar.xz`: this tarball contains
symlinks to the s6-overlay scripts so they are accessible via `/usr/bin`.
It is normally not needed, all the scripts are accessible via the PATH
environment variable, but if you have old user scripts containing
shebangs such as `#!/usr/bin/with-contenv`, installing these symlinks
will make them work.

You specifically crafted an example using `#!/usr/bin/with-contenv sh` that does not include the symlinks tarball, so no, it's not going to work 🤷

**Comment by abesnier** [comment] 2022-01-27 09:03
@skarnet Thanks for the reply. Yes, if I use the absolute path for the shell and for the service, the services start. 
There are still some path / environment variables errors later down the line. They are correctly set in the docker (at least if I check with echo $THE_VARIABLE), but seem to be ignored/returned blank when they are called in the init scripts.

Most important ones for me are JAVA_HOME, POSTGRES_USER, POSTGRES_DB. 

The script in question is like this:
```
# Create database if it does not exist
psql -U postgres -lqt | cut -d \| -f 1 | grep -qw $POSTGRES_DB
if [ $? -ne 0 ]; then
  createuser -U postgres $POSTGRES_USER
  createdb -U postgres -O $POSTGRES_USER $POSTGRES_DB
```
The problem is that the `POSTGRES_DB` already exists, so `psql -U postgres -lqt | cut -d \| -f 1 | grep -qw $POSTGRES_DB` should return 0 and the following if block should be ignored. But because at container start, `$POSTGRES_DB`  is blank, the command fails, the if block is entered, and the following commands fail because `$POSTGRES_DB` and `$POSTGRES_USER` are still blank.

However, if I enter the container, I can confirm that `JAVA_HOME`, `POSTGRES_USER`, `POSTGRES_DB `are not blank, and the services can start as expected. But I really do not want to do it manually (that would defeat the purpose of a docker container...)

So I believe that there is a bug in v3, where the environment variables are not initialized properly, and that may be linked (if not even the same bug at all), to the `with-contenv` bug you mentioned already (and in other issues I read).

**Comment by skarnet** [comment] 2022-01-27 12:42
@abesnier Importing container environment variables into service scripts is the point of `with-contenv`. Without it or `S6_KEEP_ENV=1`, services do not inherit these variables.
Can you build the latest s6-overlay from source, use `#!/command/with-contenv sh` shebangs (or `#!/usr/bin/with-contenv sh` if you use the symlinks tarball), and tell me whether it's working for you?

**Comment by abesnier** [comment] 2022-01-27 12:56
I will try and let you know.

**Comment by abesnier** [comment] 2022-01-27 15:09
Ok, tried it, and it worked, with symlinks and and `#!/command/with-contenv sh` shebang, but not with `#!/usr/bin/with-contenv sh`

**Comment by GreyXor** [comment] 2022-01-27 15:09
@skarnet 
> If it doesn't, is your service located in /usr/sbin or something similar? in that case, either use the full path to your service, or modify your script so it changes PATH to include the path to your service. The default PATH is /command:/bin:/usr/bin.

According to https://github.com/just-containers/s6-overlay/blob/master/doc/init.txt#L6 
it seems to me appropriate to modify the PATH in `/etc/s6-overlay/config/global_path` . what do you think?

**Comment by skarnet** [comment] 2022-01-27 15:42
@GreyXor If you have a lot of binaries in e.g. `/usr/sbin` and you want to add `/usr/sbin` to the PATH of all the services, then yes, modifying `/etc/s6-overlay/config/global-path` is the way to go. If you only need it for a couple services, it's probably better to only modify the PATH in the run scripts of said services.

@abesnier I'm not sure I understand your report. Here's what I expect:
- with or without the symlinks-noarch tarball: `#!/command/with-contenv sh` works
- with the symlinks-noarch tarball: `#/usr/bin/with-contenv sh` works
- without the symlinks-noarch tarball: `#!/usr/bin/with-contenv sh` does not work

If it is what you are observing, then everything is working as intended. If not, please say precisely what differs from the expected result.

**Comment by abesnier** [comment] 2022-01-27 16:04
with or without the symlinks-noarch tarball: #!/command/with-contenv sh works -> confirmed
with the symlinks-noarch tarball: #/usr/bin/with-contenv sh works -> confirmed (it did not work if I add the symlinks-**arch**)
without the symlinks-noarch tarball: #!/usr/bin/with-contenv sh does not work -> confirmed

So in the end, all your cases are confirmed to work as expected for me.

Thanks a lot for your support!

**Comment by skarnet** [comment] 2022-01-27 19:05
Awesome! Closing this issue then. 😊

**Closed by skarnet** 2022-01-27 19:05 UTC

**Comment by cafuego** [comment] 2022-01-31 01:02
Sorry to comment on a closed issue, but I have opinions after bumping my docker images to s6 version 3 :-)

It's fairly trivial to modify the /init script to honour any PATH that people are passing via an env variable, either at build time or at run time. I think breaking that functionality is not great. I would certainly expect to always be able to set environment variables at runtime and not have some that behave differently.

By changing these  lines in `layout/rootfs-overlay/init` to use a temp variable and not overwrite $PATH you can still inject the contents of global-path to the start of the $PATH variable and thus not break init scripts that use /command, but also retain what the user wanted in there:

```
- if ! read PATH < /etc/s6-overlay/config/global_path ; then
-  PATH=/bin
- fi
+ if read GLOBAL_PATH < /etc/s6-overlay/config/global_path ; then
+  PATH="$GLOBAL_PATH:$PATH"
+ fi
```

That strikes me as a better idea than requiring people (me included) to maintain custom global-path files for any number of different docker images.

**Comment by skarnet** [comment] 2022-01-31 01:48
Your patch is incorrect - you can't inherit any part of PATH from the host. But I understand what you mean: it's probably more user-friendly, indeed, to read GLOBAL_PATH from the Dockerfile than from an in-container file. Writing this down for the next version, thanks!

**Comment by colinmollenhour** [comment] 2022-02-11 22:47
@skarnet Thanks for your generosity in developing this handy tool!

Just a note that the exclusion of the `/usr/bin` symlinks makes most of the blog articles and tutorials such written about s6-overlay broken (they don't mention the symlinks package) so unless you read the entire README you can easily miss that these are no longer valid paths... might consider adding a much more prominent notice to the README for people referencing old guides so that they don't miss this like I did.

**Comment by skarnet** [comment] 2022-02-11 22:52
Will do! The documentation is the part that needs the most improvements... as usual...
