### ISSUE TITLE
This is fantastic.

### ISSUE THREAD

**Issue by smebberson** [just-containers/s6-overlay#41] opened 2015-04-22 01:56 UTC
I've been running s6 as process management for Docker for a while. It's been working extremely well. I have a vagrant machine setup to do all of this, including statically building all of the s6 binaries.

https://github.com/smebberson/docker-ubuntu-base

You can see we're making quite a collection of base images with services (redis, mongo, etc) being started by s6. It's all working great.

Can I ask a couple of questions?

It this ready to accept service directory `run`, and `finish` scripts? All of my current images are configured this way. Should I be moving to your base image, or keep using mine for now?

Also, when you CTRL+C on a running container, does s6 handle terminating all of the processes? If it does, does it execute the `finish` script within the service directory, or does that only happen when the process dies?

I'm working on a new image running Consul, and have the following `finish` script:

```
#!/usr/bin/env bash

exec s6-setuidgid consul consul leave;
```

But it never seems to execute. I know the process that was started by s6 (consul), is receiving the signal. I can confirm that, but not that the `finish` script is executed (I'm testing this by adding `echo "finish script"` to the above).

**Comment by glerchundi** [comment] 2015-04-22 05:35
Thanks for that cool issue heading :-)

> It this ready to accept service directory run, and finish scripts? All of my current images are configured this way. Should I be moving to your base image, or keep using mine for now?

Of course! This overlay is just about creating a docker oriented and rock-solid init around `s6`. It works like `s6` was designed to work just place your "user" services in `/etc/services.d` (you may find this issue interesting: #39). Take a look to this example too: [nginx-loadbalancer](https://github.com/just-containers/nginx-loadbalancer).

> Also, when you CTRL+C on a running container, does s6 handle terminating all of the processes? If it does, does it execute the finish script within the service directory, or does that only happen when the process dies?

Definitely, yes. We talked about this in this loooong thread, quite interesting reading: http://www.mail-archive.com/supervision@list.skarnet.org/msg00502.html.

> But it never seems to execute. I know the process that was started by s6 (consul), is receiving the signal. I can confirm that, but not that the finish script is executed (I'm testing this by adding echo "finish script" to the above).

Yes, they executed but you didn't notice that because stdout was previously closed and no `echo`s will be displayed, you can try it yourself creating a volume and `touch`ing a file inside the `finish` script. @skarnet already knows this behaviour. Another reference to an awesome blog post about `s6` and docker by @jprjr: http://blog.tutum.co/2014/12/02/docker-and-s6-my-new-favorite-process-supervisor/

**Comment by smebberson** [comment] 2015-04-22 06:09
@glerchundi, thanks for getting back to me so quickly, much appreciated. Thanks for your feedback, I'll do some debugging and see if it is working.

The reason I was questioning if the `finish` script was indeed being executed, is because the Consul agent isn't leaving the Consul network as it should (the command in the `finish` script tells the Consul agent to leave the Consul network properly). Leaving the Consul network does involve RPC call (all within the same VM) from one Consul agent to another though, so it may not have enough time to make the call before it's forced to quit? Could that be an issue? As you suggested, I'll `touch` a file to confirm.

I've read that blog post. That is what introduced me to `s6` and why I've put so much effort into getting all these images up and running.

I did have a question regarding `/etc/services.d/` and why that directory was chosen over `/etc/s6/services`. I have been using `/etc/s6` myself because that is the only reference on the s6 website. But issue #39 talked that through, so I can live with that.

I'll keep reading that thread you pointed me to to learn more about the design decisions behind the `s6-overlay`. It does seem a lot more complicated than what I went through to get s6 up and running in my base container, which is essentially just:

```
ENTRYPOINT ["/usr/bin/s6-svscan","/etc/s6"]
CMD []
```

With all of the s6 binaries already in `/usr/bin`. I'm no linux expert by any means, so I'm guessing there was just a lot more depth to setting up a proper environment for s6 within Docker than I went to the trouble of implementing?

Thanks for getting back to me!

**Comment by glerchundi** [comment] 2015-04-22 07:55
You're welcome.

> With all of the s6 binaries already in /usr/bin. I'm no linux expert by any means, so I'm guessing there was just a lot more depth to setting up a proper environment for s6 within Docker than I went to the trouble of implementing?

Yes there is, that's why `s6-overlay` exists!

**Comment by smebberson** [comment] 2015-04-22 08:39
Okay, so the finish script for the consul service is now:

```
#!/usr/bin/env bash

touch /data/finished

consul leave

# if Consul dies, this will force the entire container to stop
s6-svscanctl -t /etc/s6
```

To verify, I did the following:

- `docker run --name consul smebberson/consul`
- then in another terminal `docker stop`
- then back in the original terminal `docker start consul`
- then in another terminal `docker exec consul ls -l /data`

But there was no `finished` file in there. I did the same in my start script, and everything works as expected. Another thing I've noted is the output from consul when I stop the container: `==> Caught signal: terminated`. Importantly, sometimes I see this output and other times I don't.

Could it be there isn't enough time to let it execute?

Could all this be related to how I've setup s6 within my container? I guess I'll setup an image with the s6-overlay now that I know it exists and see if I experience the same thing.

**Comment by glerchundi** [comment] 2015-04-22 09:55
Weird, it should be working, I tested it again and it's working on my machine:

```
./
  Dockerfile
  rootfs/
    etc/
      services.d/
        test/
          finish
          run
```

`Dockerfile`:
```
FROM quay.io/justcontainers/base:v0.4.1
COPY rootfs /
```

`./rootfs/etc/services.d/test/run`:
```
#!/usr/bin/env bash
tail -f /dev/null
```

`./rootfs/etc/services.d/test/finish`:
```
#!/usr/bin/env bash
touch /data/was_executed
```

And executed it like this:
```
$> docker build -t test .
$> docker run -v `pwd`/data:/data test
[fix-attrs.d] applying owners & permissions fixes...
[fix-attrs.d] 00-runscripts: applying... 
[fix-attrs.d] 00-runscripts: exited 0.
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
^C[s6-finish] syncing disks.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
$> ls -l data/
total 0
-rw-r--r--  1 glerchundi  staff  0 Apr 22 11:52 was_executed
```

Can you test against `v0.4.1` of our base image or if you're using our overlay against `1.9.1.1`?

**Comment by skarnet** [comment] 2015-04-22 11:14
About the finish script print thing:
If you are using the latest version of s6 (currently 2.1.3.0), normally the "things printed by the last execution of the finish script do not appear, despite the finish script actually being executed" issue has been solved. That behaviour was a legacy solution to a problem I had earlier, and was not needed anymore. Finish scripts should now run the same way every time, whether or not it is their last execution.

About the complexity of the overlay: the hard part is to make it work in all cases. Just running s6-svscan as the entrypoint will actually work... if your use case is exactly the right one (logging everything outside of the container, a fixed set of services, no service dependencies, no one-time initialization, no Ctrl-C unless all your service directories have a nosetsid file, no interactive shell inside the container while your services are running, etc.)
The point of the overlay is to provide the amount of scripting that is needed to give some flexibility to the setup. All kudos to Gorka for identifying what is needed and for maintaining it all !

About your consul finish script: I'm not sure what the issue is, but it's definitely the wrong approach.
 - The finish script will only be executed once your daemon is dead. So, will "consul leave" do anything, since consul is supposed to be dead already ?
 - The point of a supervision system is to keep your daemons running, restarting them when they accidentally die. The finish script for a service is only there to clean up things between invocations of your service. If you bring down the whole system in a finish script, it means your service can only die once: in that case, you should simply not supervise it. If your goal is to kill everything once consul dies, then do not make consul a service: simply launch it at the end of your initialization. "docker run image consul", or whatever your consul invocation is. The overlay will launch your services, then run consul unsupervised, then automatically bring down the services when consul dies.
 If you want consul as a service, then it will keep running even if it accidentally dies, and you as the admin are the one to decide when the system must go down.

**Comment by glerchundi** [comment] 2015-04-22 13:12
@skarnet perfectly explained, as always. `1.9.1.1` already includes `s6-2.1.3.0` and it works like a charm! I've modified `finish` script to print something and it works, i didn't notice that, thanks for pointing that out.

**Comment by smebberson** [comment] 2015-04-23 02:03
@glerchundi, @skarnet 

Thanks for getting back to me. I can also confirm that everything is working as expected with s6-overlay anyway. I modified the `finish` script and it is executed as it should be, and `echo` does indeed work!

@skarnet, thanks for the advice regarding running the main process outside of s6 too. That makes a lot of sense.

@skarnet, thanks for the detailed explanation of the `finish` script. It really made things quite a bit clearer. It does beg the question however about how to manage two scenarios:

- a service accidentally dying
- a shutdown request, initiated either by CTRL+C, `docker stop container-name` or redeploying a container on production (by whatever means that happens)

I understand now that the service accidentally dying is well and truly covered and this makes a lot of sense. Create a finish script and add to it any tasks that need to occur between invocations of the service.

I'll explain my scenario a little more. [Consul](https://www.consul.io/) provides service registration and discovery. It goes hand in hand with Docker which suggests context isolation through containers (run nginx in one container, your Node.js in another container, redis in another container and your database in yet another container). There is much discussion about how much separation is good and bad. Regardless, we have a bunch of services that live on different IPs and that is where Consul comes in.

I have one container running Consul as a server. Another container running a Node.js application, and Consul as an agent. Another container running Nginx, and Consul as an agent. When the Node.js and Nginx containers start, they register there services with Consul (the container running Consul as a server). Using health checks on the container themselves, the Node.js container and Nginx container report their health to the Consul server. Everything is happy.

**This scenario is covered:** Node.js dies. The Node.js container exists and the host machine automatically brings it back up (which is the The Docker Way). The Consul server realises it is dead and tries to communicate with it. Within a few seconds, the Node.js container restarts, registers the service with the Consul server again and everything is once again happy.

**This scenario is not covered:** Node.js is brought down by me (the sys admin). When this happens, I want to issue the command `consul leave` which tells the Consul server, that the service is going away. It is expected, and don't try to contact the server because everything is good.

I'm not sure of the best way to achieve this? The command would need to be issued before:

```
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
```

**Comment by smebberson** [comment] 2015-04-23 02:05
@glerchundi, thinking this through further... would it be an extension to the `init-stage3` script to allow customisation just as `init-stage2` does with `fix-attrs.d` and `cont-init.d`?

**Comment by glerchundi** [comment] 2015-04-23 06:34
@smebberson umm, that seems an already implemented behaviour in `s6`, maybe there is a way to differentiate both, take a look at this: http://skarnet.org/software/s6/s6-supervise.html.

You can detect if finish was called because it's not going to be supervised anymore. @skarnet can you confirm that? Is this script kind of good practice in `s6`?

./rootfs/etc/services.d/test/finish:
```
#!/usr/bin/execlineb -S0
if { s6-test $# -ne 0 }
if { s6-test ${1} -eq 256 }
consul leave
```

`consul leave` will be executed if finish was called due to `docker stop`, CTRL-C or whatever graceful supervision tree shutdown.

**Comment by jprjr** [comment] 2015-04-23 12:06
I think @smebberson does bring up a good point, it would probably make sense to have the overlay do this:

* User issues `docker stop`, `SIGINT`, etc
* s6-svscan sends `TERM`s to everything
  * supervised processes run their finish scripts
* s6-svscan executes its `finish` script, which calls `init-stage3`
* [new step] `init-stage3` executes scripts in some type of `cont-finish.d` directory for final container-wide cleanup/shutdown tasks.

Both that and @glerchundi's idea should work, but having a `finish.d`-type directory might be simpler for new people to use - the documentation becomes "place scripts here, they'll run anytime the container stops"

**Comment by glerchundi** [comment] 2015-04-23 15:14
I like the idea but that should be discussed and implemented carefully! because, for example, how does the overlay behave if one of that `cont-finish.d` scripts get stuck?

**Comment by skarnet** [comment] 2015-04-23 16:08
I agree with @jprjr 's idea. If it's about running commands when exiting the container, it's cleaner to have those commands invoked by stage 3 rather than finish scripts.
About one of the scripts getting stuck... I guess that's the reason for your question on my mailing-list about `s6-maximumtime`, isn't it ? You've found the solution then :)

Finding the correct timeout for every `cont-finish.d` script may be tricky, because it can vary wildly from service to service... @smebberson , how long does `consul leave` typically take, let's say 1. when everything works as expected and 2. when the server is a bit slow to react for some reason ?

**Comment by glerchundi** [comment] 2015-04-24 06:36
> I agree with @jprjr 's idea. If it's about running commands when exiting the container, it's cleaner to have those commands invoked by stage 3 rather than finish scripts.

Ok, so if all agree, we need to make it available asap!

> About one of the scripts getting stuck... I guess that's the reason for your question on my mailing-list about s6-maximumtime, isn't it ? You've found the solution then :)

you caught me!

> Finding the correct timeout for every cont-finish.d script may be tricky, because it can vary wildly from service to service... @smebberson , how long does consul leave typically take, let's say 1. when everything works as expected and 2. when the server is a bit slow to react for some reason ?

by default, i'm going to use 5s per each script (the same value you're using for `finish` scripts).

**Comment by glerchundi** [comment] 2015-04-24 10:34
I found a free slot and I'm going to modify master to include this. I think it would be interesting to have a env var so that we can customize timeout value, can we propose env names for this?

```
S6_{FINISH,FINALIZATION}_SCRIPTS_TIMEOUT
S6_{FINISH,FINALIZATION}_SCRIPTS_GRACETIME
```

**Comment by smebberson** [comment] 2015-04-24 11:55
Awesome! My vote is for:

> S6_{FINISH,FINALIZATION}_SCRIPTS_TIMEOUT

**Comment by glerchundi** [comment] 2015-04-24 15:36
merged (#45) and released: `1.9.1.3`!

I've chosen this: `S6_KILL_FINISH_MAXTIME` because I wanted to specify what it does but thanks anyway :+1: 

I've tested it so I'm going to close this, ok?

**Comment by smebberson** [comment] 2015-04-27 00:29
@glerchundi, thank you for doing this. I'm integrating it as we speak.

I've had a look at the source code and wanted to ask a question, it seems as though the scripts (if there are any) in `/etc/cont-finish.d/` will run regardless of how the container is exiting?

For the discussion, there are two types of exits:

- brought down by the administrator (either via CTRL + C or `docker stop`)
- brought down as a result of a process dying (i.e. using `CMD ['nginx']` in the Dockerfile)

My original query was regarding to being brought down by the administrator. In this scenario, I wanted to run `consul leave`. As pointed out by @skarnet, if the main process (i.e. consul) died, there wouldn't be a point in running `consul leave` because consul wouldn't be running.

With the code you've implemented, correct me if I'm wrong, it seems we're in the same scenario other than the fact we have scripts in `/etc/cont-finish.d/` rather than `/etc/services.d/service/finish`.

**Comment by jprjr** [comment] 2015-04-27 13:35
@smebberson would this solve your problem? https://www.consul.io/docs/agent/options.html#leave_on_terminate

Consul has an option to leave when it receives a `TERM` signal, instead of going into the `failed` state

**Comment by smebberson** [comment] 2015-04-28 03:19
@jprjr Thanks for that. I missed that in the documentation, but it is good to know. I've just gone through and read through every single option and configuration. I also found https://www.consul.io/docs/agent/options.html#skip_leave_on_interrupt but I still can't get Consul to leave properly on both types of shutdown.

**Comment by glerchundi** [comment] 2015-04-28 10:40
@smebberson ah! i missed the point completely, what you really want is something like a signal wrapper/processor which, of course, is not solved using what I've implemented...with the doc pointed by @jprjr it should solve your use case. What I really don't know is if this is just a concrete and special use case or just a common one. If someone else is facing this error we'll think about a generic solution although I don't know if it can be done in a elegant way...

**Comment by skarnet** [comment] 2015-04-28 20:01
A solution to differentiate both cases: put a flag in stage 2, and test for it in stage 3.
- towards the beginning of stage 2, clear the flag: `if { s6-mkdir -p /var/run/s6/env-stage3 } if { redirfd -w 1 /var/run/s6/env-stage3/S6_DOCKER_CMD_EXITED s6-echo false } `
- at the point of stage 2 where cmd exits, right before s6-svscanctl -t, set the flag: `foreground { redirfd -w 1 /var/run/s6/env-stage3/S6_DOCKER_CMD_EXITED s6-echo true }`
- at the top of init-stage3, read the flag (actually a whole set of stage3-specific environment variables, in case we need more later on):  `s6-envdir -I /var/run/s6/env-stage3`

Then any script executed in stage 3, including the `/etc/cont-finish.d/` ones, will be able to test the `S6_DOCKER_CMD_EXITED` environment variable and adjust their behaviour accordingly. In @smebberson 's case, his `/etc/cont-finish.d/consul` script would only run `consul leave` if `$S6_DOCKER_CMD_EXITED` is false.

**Comment by jprjr** [comment] 2015-04-28 22:14
I think (if I'm reading @smebberson correctly) the problem is this: The `consul leave` command expects that your consul agent is still running when you execute `consul leave`

So, here's the scenario:

1. @smebberson has a container running two services, `nginx` and `consul`
2. If `nginx` craps out, it executes into it's `finish` script, which is something like:
```
#!/bin/sh
consul leave
s6-svscanctl -t /var/run/s6/services
```

If instead he issues `docker stop`, the following happens:
1. `s6-svscan` sends a `TERM` signal to all the `s6-supervise` processes
  * An `s6-supervise` sends a `TERM` to consul
  * Another `s6-supervise` sends a `TERM` to nginx

At this point, it doesn't matter if he tries to run `consul leave` in the nginx `finish`, the `consul` finish, or the `cont-finish.d`, because consul has already died and `consul leave` will fail. `consul leave` basically just tells the running agent to leave the cluster.

At least, I *think* that's the problem. You'd almost want `s6-svscan` to have some way of running a script before sending the TERM signal to all it's supervised processes, so you can run `consul leave` before sending TERM signal.

**Comment by smebberson** [comment] 2015-04-29 02:36
@skarnet, that sounds perfect.

@jprjr, you're correct in your explanation of the problem, aside from one point. The order you explained things happen in:

- docker stop
- s6-svscan sends a TERM
- service directory finish, and then cont-finish.d

But in practice, it works in this order (@glerchundi correct me if I'm wrong):

- docker stop
- cont-finish.d scripts are executed
- s6-svscan sends a TERM signal

So, the actual order it does run in does allow us to benefit from the additional items @skarnet mentioned above, and issue a `consul leave` only if the S6_DOCKER_CMD_EXITED variable is false. So that would work perfectly.

@jprjr, just to be clear:

"You'd almost want s6-svscan to have some way of running a script before sending the TERM signal to all it's supervised processes, so you can run consul leave before sending it a TERM signal."

You can actually do that with the way it's been programmed today, with the scripts that you put in cont-finish.d.

I hope this helps.

**Comment by glerchundi** [comment] 2015-04-29 07:25
**TL;TR.**

I agree with @jprjr.

We're facing two kind of problems here:
* Differentiate between a brought down by admin (`CTRL+C`, `docker stop` or `s6-svscanctl -t`) or as a result of user provided (through `CMD`) process dying.
* Being able to execute some post-signal code but just before terminating some process.

The first one is easily solved with @skarnet's solution, it would provide information on how it was executed, and you could act in consequence. *BUT it doesn't solve your problem* because actually `s6` is executed in the order @jprjr has explained (correct us if we're wrong @skarnet):

* `docker stop` (`SIGTERM` sent to PID 1 -`s6-svscan`)
* `s6-svscan` sends a `TERM` to all services (which are supervised by `s6-supervise`)
* for each `s6-supervise`, a `TERM` signal is sent to your custom process and inmediately `./finish` is executed, which could take at most 5 seconds to end before sending a `KILL` signal.
* once all `./finish` scripts ended, `/var/run/s6/services/.s6-svscan/finish` is executed which points to `/etc/s6/init/init-stage3`which....
* then, and finally, executes all scripts included in `cont-finish.d`.

Empirically I tested it and seems to work as I explained, with a slightly (very important for the case that concerns us) different behaviour. Actually, it seems that `s6` spawns `finish` scripts in parallel (including `.s6-svscan` one), which could fall into a race condition between `cont-init.d` scripts and `finish` scripts. 

Just to put everything into context I created an example that illustrates the race-condition I mention:

`./Dockerfile`:
```
FROM quay.io/justcontainers/base:v0.5.0
COPY rootfs /
```
`./rootfs/etc/cont-finish.d/00-test`:
```
#!/usr/bin/execlineb -P
s6-echo "from cont-finish.d"
```
`./rootfs/etc/services.d/test/finish`:
```
#!/usr/bin/env bash
trap "sigterm received" SIGTERM
trap "sighup received" SIGHUP
s6-pause # stop until a signal is received, just to force the race condition
s6-echo "hello from service ./finish"
exec s6-pause -th
```
`./rootfs/etc/services.d/test/run`:
```
#!/usr/bin/execlineb -P
tail -f /dev/null
```

And if I execute this sequence:
* `docker run -ti -e S6_KILL_GRACETIME=10000 test` (10s just to let `s6` kill this `./finish` process because it exceeded its internal timeout of 5s).
* `docker stop` from another terminal

```
$> docker run -ti -e S6_KILL_GRACETIME=10000 test
[fix-attrs.d] applying owners & permissions fixes...
[fix-attrs.d] 00-runscripts: applying... 
[fix-attrs.d] 00-runscripts: exited 0.
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 00-test: executing... 
from cont-finish.d
[cont-finish.d] 00-test: exited 0.
[cont-finish.d] done.
[s6-finish] syncing disks.
[s6-finish] sending all processes the TERM signal.
Hangup
sighup received
sigterm received
hello from service ./finish
s6-supervise test: warning: finish script takes too long - killing it
[s6-finish] sending all processes the KILL signal and exiting.
```

However, if (in the service `./finish` script) we had performed just an "echo", things seem to run in the order that mentioned above:
`./rootfs/etc/services.d/test/finish`:
```
#!/usr/bin/execlineb -P
s6-echo "hello from service ./finish"
```

```
$> docker run -ti -e S6_KILL_GRACETIME=10000 test
[fix-attrs.d] applying owners & permissions fixes...
[fix-attrs.d] 00-runscripts: applying... 
[fix-attrs.d] 00-runscripts: exited 0.
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
hello from service ./finish
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 00-test: executing... 
from cont-finish.d
[cont-finish.d] 00-test: exited 0.
[cont-finish.d] done.
[s6-finish] syncing disks.
[s6-finish] sending all processes the TERM signal.
```

Ok, that being said, we cannot assure that, even if we detect how was our container brought down, `consul leave` will work (if it was executed through a `cont-finish.d` script), because your main `consul` service is already dead.

Now the second part and, if it would be possible, should solve your problem. Imagine that we have a service which doesn't have that convenient way of doing the shutdown (that `leave_on_terminate` in the configuration file). We could have some utility which inserts a hook between receiving a signal and the forwarding to the final process. Something like this:

`s6-signal-hook -t { /* code to be executed before TERM (-t) forwarding */ } main-process`

In your use case it would be something like this:

`s6-signal-hook -t { consul leave } consul whatever`

This should solve most use cases, yours included. Another thing is if it's a good pattern or just a clear example of a shitty solution.

Hope it helps!

**Comment by smebberson** [comment] 2015-04-29 07:30
@glerchundi, in your output above, doesn't the fact that `[cont-finish.d] executing container finish scripts...` appears before `[s6-finish] sending all processes the TERM signal.` mean that cont-finish.d scripts execute before s6-svscan sends through TERM signals?

**Comment by skarnet** [comment] 2015-04-29 07:32
@jprjr Ah, now I get it. Thanks.

@smebberson That's incorrect. The TERM signal is sent to all services as soon as the `s6-svscanctl -t` command is run, and then s6-svscan executes into init-stage3, which runs the `cont-finish.d` scripts. If you observe otherwise, it's because there is no synchronization, and your services take ages to process the SIGTERM and die, so stage 3 starts running prior to your services' death.
 This is a race condition, it's not guaranteed behaviour. We should probably eliminate the race by waiting for all the deaths at the start of stage 3 - but then, your problem would reappear.

 Hmmm, this is not easy. What you want is for `docker stop` to actually run another command before killing everything, but all `docker stop` does is send a SIGTERM to s6-svscan, and all s6-svscan does when it receives a SIGTERM is kill everything first, then execute into stage 3. As @jprjr says, the real solution would be to insert a command to run in-between the reception of SIGTERM by process 1 and the propagation of SIGTERM to all services.

Gah, you guys are updating the thread live while I'm typing this. Posting first, more thoughts later.

**Comment by glerchundi** [comment] 2015-04-29 07:36
nope @smebberson, the TERM is sent before, that is just a [`s6-nuke`](http://skarnet.org/software/s6-portable-utils/s6-nuke.html) to all container process, first [gracefully](https://github.com/just-containers/s6-overlay/blob/master/builder/overlay-rootfs/etc/s6/init/init-stage3#L42) using TERM and then [forcibly](https://github.com/just-containers/s6-overlay/blob/master/builder/overlay-rootfs/etc/s6/init/init-stage3#L57) using KILL.

**Comment by glerchundi** [comment] 2015-04-29 07:37
@skarnet we've had a race condition between us, haha!

**Comment by smebberson** [comment] 2015-04-29 07:37
@skarnet, actually, I have noted the TERM signal is being sent to all services immediately. Consul kept outputting that it caught TERM signal and exited, way before my scripts had a chance to run - which was frustrating for my use case.

@glerchundi, yep, it's becoming clearer to me now. Thanks for clarifying. Sorry @jprjr for thinking you were wrong! How silly of me :)

**Comment by smebberson** [comment] 2015-04-29 07:40
@skarnet, @jprjr, @glerchundi

"As @jprjr says, the real solution would be to insert a command to run in-between the reception of SIGTERM by process 1 and the propagation of SIGTERM to all services."

Yeah, that would be a perfect solution.

**Comment by skarnet** [comment] 2015-04-29 08:09
When I first read runit's [runsv](http://smarden.org/runit/runsv.8.html) manual page, I wondered about the [Customize Control](http://smarden.org/runit/runsv.8.html#sect4) section: in what situation could that possibly be useful? It looked like useless bloat to me. So I didn't add that functionality to s6-supervise.
This is the first time I encounter a real case where this would help. I should give Gerrit credit, he saw that and I didn't.

 Still, I don't want to add the functionality in this way. User-defined scripts cannot be relied on, and tightly integrating them into a supervisor is a liability. What if they block? Should the supervisor kill them? With what timeout? What should it do in the meantime? Those are questions that cannot be answered in all genericity, and trying to do so would make s6-supervise a lot more complex than it currently is, for a benefit that's really not reaped often.

 It sounds to me that since the issue is specific to one service, the solution can also be specific to that service. Namely, trap SIGTERM just for consul. I normally advise *against* keeping a shell around in run scripts, because it precisely messes with signals sent by s6-supervise, but here it would be useful. @smebberson , if we add the flag thing to the overlay, you should be able to replace your consul run script with something like:
```sh
#!/bin/sh

pid=$$

sigterm()
{
  if $(cat /var/run/s6/env-stage3/S6_DOCKER_CMD_EXITED) ; then
    :
  else
    consul leave
  fi
  kill -TERM $pid
}

trap sigterm SIGTERM
consul whatever-options &
pid=$!
wait
```
which will work if you have no intention of directly controlling your consul service via `s6-svc` commands and can be reasonably sure that no SIGKILL will ever reach it.

**Comment by glerchundi** [comment] 2015-04-29 11:41
@skarnet what about something like this in `s6-portable-utils`? ;))

```
# -m: max timeout
# -t: trap SIGTERM
s6-trap -m 5000 -t
{
  if { s6-test -f cat /var/run/s6/env-stage3/S6_DOCKER_CMD_EXITED }
  consul leave
}
consul whatever-options
```

@smebberson @jprjr @skarnet may I close this? silence means yes...

**Comment by jprjr** [comment] 2015-04-29 12:02
@glerchundi Sure!

@skarnet that script is awesome. Also, I like @glerchundi's idea, or alternative: it'd be really cool to have some way of telling `s6-supervise` to send a different signal (in this case, consul should do the "graceful shutdown" when it receives an `INT` signal). Make there could be a file in the service directory to specify what signal to send?

**Comment by skarnet** [comment] 2015-04-29 12:55
@glerchundi I would definitely write a s6-trap utility if it was possible. Unfortunately, it's not: traps do not survive [execve()](http://pubs.opengroup.org/onlinepubs/9699919799/functions/execve.html), so to handle traps outside of a program, you have to fork, exec the child, and set traps in the parent - this is exactly what the shell does, and is one of the few cases where the shell's design makes total sense. I can't do any better than the shell here.

But if consul can shutdown gracefully when it receives another signal than SIGTERM, I can mix that idea with @jprjr 's one. Stay tuned, I'll come up with something.

 Sure, close the issue, but please implement the flag thingy, so we can solve @smebberson 's problem without relying on the race condition!

**Comment by glerchundi** [comment] 2015-04-29 13:00
> @glerchundi I would definitely write a s6-trap utility if it was possible. Unfortunately, it's not: traps do not survive execve(), so to handle traps outside of a program, you have to fork, exec the child, and set traps in the parent - this is exactly what the shell does, and is one of the few cases where the shell's design makes total sense. I can't do any better than the shell here.

Perfect!

> Sure, close the issue, but please implement the flag thingy, so we can solve @smebberson 's problem without relying on the race condition!

Will do. Thanks all for your collaboration!

**Closed by glerchundi** 2015-04-29 13:00 UTC

**Comment by glerchundi** [comment] 2015-05-05 10:38
@skarnet #49 merged, it adds S6_CMD_EXITED env in stage3 which contains CMD exit code.

**Comment by glerchundi** [comment] 2015-05-06 08:04
@smebberson with the latest release you can achieve this behaviour (thanks @skarnet for [`trap`](http://skarnet.org/software/execline/trap.html) utility!)

In your run script do this:
```
#!/usr/bin/execlineb -P
trap
{
  term
  {
    foreground { consul leave }
    import -u ! kill ${!}
  }
}
consul whatever-options
```

Cool!

**Comment by smebberson** [comment] 2015-05-06 08:07
@glerchundi, @skarnet, @jprjr 

That is awesome! This will help to create super concise and easy to follow containers. Thank you!

**Comment by skarnet** [comment] 2015-05-06 14:21
@smebberson , @glerchundi : the run script should probably be a bit more complex than that, since it must only call `consul leave` if the SIGTERM comes from the admin shutting down the container, and not a CMD exiting. So in the `foreground` block, I'd add something like `if { s6-test ! -f /var/run/s6/env-stage3/S6_CMD_EXITED }` before the `consul leave`. (AIUI, the `S6_CMD_EXITED` file is only created when a CMD actually exits, and contains its exit code, which is of no interest here.)
