### ISSUE TITLE
Proposal: `S6_VERBOSITY` or something like this, to configure logging levels

### ISSUE THREAD

**Issue by glerchundi** [just-containers/s6-overlay#32] opened 2015-03-31 21:26 UTC
ideas are welcome :-), coming from #25

**Comment by joeblackwaslike** [comment] 2015-12-16 22:08
i see this is old but i wouldn't mind resurrecting it. I just started using s6-overlay and to be honest, the name S6_USE_CATCHALL_LOGGER is confusing. I don't remember a catchall logger being mentioned in the documentation. A wise person once said the only two difficult things in computer science are naming things, and cache invalidation. 

My first experience using s6-overlay in a container was doing a docker run -it --rm image bash to get a shell and verify that all my scripts ran without error. It was then I discovered s6 is very verbose by default. Which I don't mind, but it's typically not a unix/linux convention to be so verbose on stdout by default.  

Just my 2 cents, keep up the good work. After I'm more familiar with using s6 I will surely make some contributions down the road, it's quite a worthy project :)

**Comment by glerchundi** [comment] 2015-12-17 07:53
@joeblackwaslike and thats why we refactored that env to `S6_LOGGING` as stated in the [`README`](https://github.com/just-containers/s6-overlay#customizing-s6-behaviour) :-)

> My first experience using s6-overlay in a container was doing a docker run -it --rm image bash to get a shell and verify that all my scripts ran without error. It was then I discovered s6 is very verbose by default. Which I don't mind, but it's typically not a unix/linux convention to be so verbose on stdout by default.

It is, any proposal is welcome.
 
> Just my 2 cents, keep up the good work. After I'm more familiar with using s6 I will surely make some contributions down the road, it's quite a worthy project :)

Yep, Thanks!

**Comment by skarnet** [comment] 2016-03-03 20:41
s6, very verbose? By default, the s6 programs only print messages to stderr when something's wrong, and they never print anything to stdout. They're following the Unix conventions to the letter.
Do you mean that the s6-overlay scripting is verbose?

**Comment by glerchundi** [comment] 2016-03-11 10:41
The verbosity comes from `s6-overlay` not from `s6`. I did it in this way based on `phusion/baseimage-docker` was already doing and to somehow equate both projects. But maybe it was a wrong default for the overlay.

**Comment by thoughtarray** [comment] 2016-08-23 17:26
I'm way late, but the issue is still open.  If you look at the ContainerPilot project's [logging settings](https://www.joyent.com/containerpilot/docs/configuration#-code-logging--code-), you'll see that the user can control some things.  Format is important imo because Docker log collectors might expect to see the output to be of a certain format.  Log level is a nice-to-have as well.

**Comment by shesek** [comment] 2021-02-04 13:41
In case anyone else might want it useful, I ended up using this (hairy) hack to reduce s6-overlay's verbosity:

```bash
sed -ri '/\[(cont-finish\.d|fix-attrs\.d|cont-init\.d|services\.d|cmd)\] /d' /etc/s6/init/init-stage{2,3}
```

This doesn't hide the `[s6-finish]` messages, which I find informative and useful.

**Comment by skarnet** [comment] 2022-01-20 10:59
s6-overlay v3.0.0.0 is out, which should significantly reduce the verbosity (only a few messages from s6-rc at startup and shutdown time).
Closing this, please reopen if there's still an issue.

**Closed by skarnet** 2022-01-20 10:59 UTC
