### ISSUE TITLE
Gitlab-runner not passing a -tty session => S6 not reading STDIN

### ISSUE THREAD

**Issue by skapin** [just-containers/s6-overlay#413] opened 2022-02-16 14:57 UTC
We are running an S6-overlay image on our CI/CD on gitlab. the script session is ignored by the running s6 container because gitlab create a container without the --tty flag. It gives the container all scripts command from STDIN.

I can't override the entrypoint because I need the with-env shebang on somes scripts.
So I let /init as entry point, but calling /bin/bash as parameter or bin/bash -c doesnt work. 

The container pop then die ignoring the stdin cmd

![output_docker](https://user-images.githubusercontent.com/1846729/154291095-53143d48-2ee7-47d5-bb81-dead4edabe76.png)

So at this moment I have 0 way to run cmd on a S6 container and keeping his env. Do you have any idea or plan to fix this ?

Related : https://gitlab.com/gitlab-org/gitlab-runner/-/issues/2115

**Comment by skarnet** [comment] 2022-02-16 15:12
I can confirm that s6-overlay does not currently pass stdin to the user scripts when the container is not run in a terminal.
I didn't think it would be an issue, because containers are meant to be run in isolation, not to take input from the outside; gitlab should find another way to transmit commands.
But since there's a need, we will make this available in a future version. Thanks for the report.

**Comment by skapin** [comment] 2022-02-16 15:32
Thank you ! Yes I do agree with you about gitlab passing stdin <_< ...

**Comment by skarnet** [comment] 2022-02-27 03:25
The current source version of s6-overlay should now correctly pass the container's stdin to the CMD. Release 3.1.0.0 is planned soon.
Closing this, please reopen if it's not fixed in 3.1.0.0, or earlier if you build from current source.

**Closed by skarnet** 2022-02-27 03:25 UTC
