### ISSUE TITLE
fix-attrs broken in v2.2.0.1

### ISSUE THREAD

**Issue by b-m-f** [just-containers/s6-overlay#329] opened 2021-02-14 19:00 UTC
I am using the `fix-attrs.d` directory to change permissions on a file that is mounted into the container at launch.

This worked fine in `2.1.0.2` but breaks in `2.2.0.1`.

**Working in 2.1.0.2**
https://github.com/b-m-f/WirtBot/runs/1894909984#step:3:1813

**Breaking with 2.2.0.1**
https://github.com/b-m-f/WirtBot/runs/1898569667?check_suite_focus=true#step:3:2244

**Comment by b-m-f** [comment] 2021-02-14 19:39
Let me know if there is any more info I can provide to help.

The only suspect I could make out is this change: https://github.com/just-containers/s6-overlay/commit/3e7bc9ff3a982137b9f16d09c02ca31ab81fe392

**Comment by jprjr** [comment] 2021-02-15 21:42
Can you come up with a small example? I can't seem to get it to fail

**Comment by b-m-f** [comment] 2021-02-16 18:34
Hi @jprjr ,

I have created a reproduction at https://github.com/b-m-f/s6-overlay-bug-reproduction . It is based on the nginx example from the README.

Simply clone and run `docker-compose up`.

**Versions:**
Docker version 20.10.3
docker-compose version 1.28.2

**Comment by rakheshster** [comment] 2021-02-21 18:10
FWIW I too encountered this issue with my containers today. Upgraded to the latest 2.2.0.3 and that didn't help either.

Docker version 20.10.2, build 2291f61
docker-compose version 1.27.4, build 40524192

**Comment by andrewzah** [comment] 2021-03-11 21:35
fix-attrs.d just hangs for me. on `2.2.0.1` and `2.2.0.3`
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
```

**Comment by timothydlister** [comment] 2021-03-12 18:02
Not sure if this will help anyone but I had this problem when using the package in the Alpine repository. When I installed using a release from this repo, the problem went away.

**Comment by dermotbradley** [comment] 2021-03-12 18:42
> On Friday, March 12, 2021, 6:03:03 PM GMT, Timothy Lister ***@***.***> wrote: 
>
> Not sure if this will help anyone but I had this problem when using the package in the Alpine
> repository. When I installed using a release from this repo, the problem went away.

Hi there, Alpine maintainer for s6-overlay here.

Which Alpine release was this with? Edge? v3.13.0/v3.13.1/v3.13.2?

Which version of the s6-overlay package? Which version of s6-overlay?

Alpine Edge has the current release of s6-overlay packaged whereas v3.13.x has an older version, likewise the version of the other s6 packages differ between Edge and v3.13.x.

Dermot

**Comment by timothydlister** [comment] 2021-03-12 18:56
> 
> On Friday, March 12, 2021, 6:03:03 PM GMT, Timothy Lister ***@***.***> wrote: Not sure if this will help anyone but I had this problem when using the package in the Alpine repository. When I installed using a release from this repo, the problem went away.
> Hi there, Alpine maintainer for s6-overlay here. Which Alpine release was this with? Edge? v3.13.0/v3.13.1/v3.13.2? Which version of the s6-overlay package? Which version of s6-overlay? Alpine Edge has the current release of s6-overlay packaged whereas v3.13.x has an older version, likewise the version of the other s6 packages differ between Edge and v3.13.x. Dermot

Hi there,

I just reran my test to make sure, from my dockerfile:
```
FROM alpine:3.13
RUN apk add --no-cache s6-overlay
...
ENTRYPOINT ["/init"]
```

Shows when run:
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
```

From inside 3.13:
```
/ # apk info s6-overlay
WARNING: Ignoring https://dl-cdn.alpinelinux.org/alpine/v3.13/main: No such file or directory
WARNING: Ignoring https://dl-cdn.alpinelinux.org/alpine/v3.13/community: No such file or directory
s6-overlay-2.1.0.0-r1 description:
s6 overlay for containers

s6-overlay-2.1.0.0-r1 webpage:
https://github.com/just-containers/s6-overlay/
```

Trying with alpine:edge gives:
```
export: fatal: unable to exec /etc/s6/init/init-stage1: Permission denied
```

**Comment by dermotbradley** [comment] 2021-03-12 19:21
> On Friday, March 12, 2021, 6:57:04 PM GMT, Timothy Lister ***@***.***> wrote: 
>
> Trying with alpine:edge gives:
> export: fatal: unable to exec /etc/s6/init/init-stage1: Permission denied

Ah, I see the problem with that, several files that should be marked executable are not:

/etc/s6/init-no-catchall/init-stage1
/etc/s6/init-no-catchall/init-stage2
/etc/s6/init/init-stage1
/etc/s6/init/init-stage3

and possibly some other files. When I create the Alpine package I unpack the upstream tarfile and any file permissions come from this tarfile. I'll raise an Issue in Github s6-overlay to log this.

Separately I'll fix this in the Alpine package and push out a new minor release for Edge - hopefully tonight, if not then tomorrow.

Looks like this has been an issue for the last few s6-overlay versions - unfortunately I've been busy with some other stuff and haven't been actively using s6-overlay for the past couple of months and so didn't spot this earlier.

Dermot

**Comment by dermotbradley** [comment] 2021-03-13 03:06
@timothydlister

I've figured out the problem with the Alpine Edge package for s6-overlay and raised a MR for a new package release to resolve it in Edge, https://gitlab.alpinelinux.org/alpine/aports/-/merge_requests/19251. I'm not part of the core Alpine and so can't do the merge myself - hopefully it will be merged in the next few hours and then the revised package will be rolled out to the repository mirrors, however it might take a day or two with it being the weekend.

In the meantime you could modify your Dockerfile for Alpine Edge to do the ``chmod`` and ``mkdir`` commands after the "apk add" for s6-overlay as a workaround.

I haven't looked at the older package for Alpine 3.13 yet but its probably the same issue.

I've raised #334 regarding the s6-overlay Source Code tarfile i'm using for the packaging.

**Comment by cnt0** [comment] 2021-03-18 10:13
looks like I can reproduce this issue with s6-overlay [package](https://pkgs.alpinelinux.org/package/v3.13/community/x86_64/s6-overlay) from alpine:3.13.
```dockerfile
FROM alpine:3.13
RUN apk add --no-cache s6-overlay
ENTRYPOINT ["/init"]
```
just hangs.  @dermotbradley can you please fix this as well?

**Comment by dermotbradley** [comment] 2021-03-19 01:17
> looks like I can reproduce this issue with s6-overlay [package](https://pkgs.alpinelinux.org/package/v3.13/community/x86_64/s6-overlay) from alpine:3.13.
> 
> ```dockerfile
> FROM alpine:3.13
> RUN apk add --no-cache s6-overlay
> ENTRYPOINT ["/init"]
> ```
> 
> just hangs. @dermotbradley can you please fix this as well?

Hi. The issue I fixed in Alpine Edge was a packaging mistake which caused the "export: fatal: unable to exec /etc/s6/init/init-stage1: Permission denied" error that @timothydlister saw. This packaging issue is not present in s6-overlay for Alpine 3.13.

As the original problem report for this ticket was observed on Debian then I don't believe the underlying issue is Alpine-specific.

**Comment by andrewzah** [comment] 2021-03-19 13:54
This happens on debian, alpine, and centos for me. I build it from source, so I don't think it's a packaging issue.

**Comment by dermotbradley** [comment] 2021-03-20 22:15
> This happens on debian, alpine, and centos for me. I build it from source, so I don't think it's a packaging issue.

I found some time to look at the underlying issue and its not a packaging issue.

Using the reproduction repo of @b-m-f which is Ubuntu based I saw the same error. However the fix is simple - the "fix-mounted" file in that repo simply needs a newline added and it works! I also created an Alpine 3.13-based version of this "reproducer" and it failed in the same way until I added a newline to that file and then it also worked.

**Comment by mustanggb** [comment] 2021-03-24 19:12
Think I just encountered this as well in docker with alpine 3.13 and s6-overlay v1.22.1.0

**Dockerfile**
```
FROM alpine:3.13

ADD https://github.com/just-containers/s6-overlay/releases/download/v1.22.1.0/s6-overlay-nobin.tar.gz /tmp/
RUN apk add --no-cache s6 s6-portable-utils && \
    tar -xzC / -f /tmp/s6-overlay-nobin.tar.gz && \
    rm /tmp/s6-overlay-nobin.tar.gz

ENTRYPOINT /init
```

Gets stuck on...
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
```

Switching to alpine 3.12 and it works fine again.

**Comment by dermotbradley** [comment] 2021-03-25 02:20
@mustanggb

> ADD https://github.com/just-containers/s6-overlay/releases/download/v1.22.1.0/s6-overlay-nobin.tar.gz /tmp/

You used this repo's "**nobin**" tarfile which only contains the s6-overlay specific files. If using this file fails but then using the same version of the "**amd64**" tarfile (obviously not then using "apk add" for the s6/s6-portable-utils packages) from this repo does work then that points to a version compatibility issue with the OS' (in this case Alpine's) versions of s6/execline/etc packages.

> @dermotbradley Maybe consider updating your [s6-overlay package in 3.13 to 2.2.x.x](https://gitlab.alpinelinux.org/alpine/aports/-/issues/12547)

I have replied to the Alpine gitlab issue you raised about this issue. I don't want to fill up this repo's issue with Alpine-specific discussions so we can talk further about it in that Gitlab issue.

Fundamentally when execline 2.7.0.0 came it out it changed some behaviour that then had to be fixed in s6-overlay (#317, #319), then when execline 2.8.0.0 came out it also changed some behaviour that required other s6-overlay changes (#335).

In general there is always likely to be some sort of time delay from whenever newer versions of s6 utilities are released and then when s6-overlay is updated to handle any changes (if needed).

**Comment by cnt0** [comment] 2021-03-25 04:00
> Fundamentally when execline 2.7.0.0 came it out it changed some behaviour that then had to be fixed in s6-overlay

ah yes. Looks like [this comment](https://github.com/just-containers/s6-overlay/issues/317#issuecomment-761867145) describes the exact problem I faced. [This](https://github.com/just-containers/s6-overlay/commit/3e7bc9ff3a982137b9f16d09c02ca31ab81fe392) is the commit which fixes that. Guys, can please reference such important issues in commit messages? It would've been so much easier to get the full picture in this case,,,

**Comment by pvizeli** [comment] 2021-03-26 11:14
I have the same issue on 2.2.x.x like:
https://github.com/b-m-f/s6-overlay-bug-reproduction

I use alpine/debian/ubuntu with the tarfile from this repository:
https://github.com/home-assistant/docker-base

**Comment by jprjr** [comment] 2021-03-26 12:00
Hi all, I think there's a lot of comments in this issue that may be specific to alpine's package of s6-overlay. I think @b-m-f provided an example that narrows the issue down.

I'm pretty sure the core issue is how execline-2.7.0.0 changed handling non-existant and empty files on the forstdin program, and fix-attrs needs to be updated to handle that.

Please give me some time and I'll address it when I can.

On March 26, 2021 7:14:21 AM EDT, Pascal Vizeli ***@***.***> wrote:
>I have the same issue on 2.2.x.x like:
>https://github.com/b-m-f/s6-overlay-bug-reproduction
>
>I use alpine/debian/ubuntu with the tarfile from this repository:
>https://github.com/home-assistant/docker-base
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/just-containers/s6-overlay/issues/329#issuecomment-808130230

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by jprjr** [comment] 2021-03-26 13:18
Here's some notes

fix-attrs has two places that uses `forstdin`.

There's a chunk that tests if a file is a directory, calls `s6-ls`, then loops over the contents of that - https://github.com/just-containers/s6-overlay/blob/51467be3d14568e821d018fbb6ffeaf79479ef80/builder/overlay-rootfs/usr/bin/fix-attrs#L17

`forbacktickx` is really just `pipeline { stuff } forstdin`

If something is an empty directory, `s6-ls` returns no output.

Before execline 2.7.0.0, `forstdin` would accept empty input and just not run the loop. Now, the input is empty, it exits 1.

The other place is https://github.com/just-containers/s6-overlay/blob/51467be3d14568e821d018fbb6ffeaf79479ef80/builder/overlay-rootfs/usr/bin/fix-attrs#L32 - this is where it reads the contents of a file from the fix-attrs.d.

Previously, if a file did not end in a newline character (like in the repo @b-m-f created), `forstdin` would still return the line. Now, if the file does not end in a newline character, `forstdin` exits 1.

**Comment by jprjr** [comment] 2021-04-10 17:24
I've been reviewing this, and I think the only real fix is to rewrite `fix-attrs` from scratch. That difference in behavior with the latest execline makes this particularly difficult.

In most other cases, I was able to replace `forstdin` with `elglob` and loop over that. But `fix-attrs` has the feature of traversing hidden files, so `elglob` just won't really work. I don't know if I can write a glob pattern that will match regular files and hidden files, while also excluding the `.` and `..` entries. `s6-ls` can do it, but then we're back at the original problem of empty directories - `s6-ls` will return empty output, so `forstdin` returns 1.

I think the better solution is to just write a custom program in C and include it as a static binary.

**Comment by pvizeli** [comment] 2021-09-07 08:02
@skarnet, if this change a bug or somethings wanted?

**Comment by jprjr** [comment] 2021-11-23 22:49
Hi all, I believe I've come up with a fix for this and could use help testing.

I've made a fork of forstdin that re-enables some of the old behavior (reading in 0 bytes of input is fine, missing a final newline is also fine), and made a branch of `s6-overlay` that uses the fork.

Here is a n example Dockerfile for installing the from the latest build off the `issue-329` branch:

```
FROM ubuntu
RUN apt-get update && apt-get install -y unzip curl

RUN curl -R -L -o /tmp/dist.zip \
  https://nightly.link/just-containers/s6-overlay/workflows/all/issue-329/dist.zip

RUN cd /tmp && unzip dist.zip && chmod +x s6-overlay-amd64-installer && /tmp/s6-overlay-amd64-installer /
ENTRYPOINT ["/init"]
```

If anybody out there can try this out and see if it fixes their issue, that would be a huge help!

**Comment by ByJacob** [comment] 2021-12-11 16:13
Works for me. Use newest `php:apache` for base.

v2.2.0.3
```
app_1  | [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
app_1  | [s6-init] ensuring user provided files have correct perms...exited 0.
app_1  | [fix-attrs.d] applying ownership & permissions fixes...
app_1  | [fix-attrs.d] 01-fix-index.php: applying... 
app_1  | [fix-attrs.d] 01-fix-index.php: exited 1.
app_1  | [fix-attrs.d] 02-fix-www-catalog: applying... 
app_1  | [fix-attrs.d] 02-fix-www-catalog: exited 1.
app_1  | [fix-attrs.d] done.
app_1  | [cont-init.d] executing container initialization scripts...
app_1  | [cont-init.d] done.
app_1  | [services.d] starting services
app_1  | [services.d] done.
```

issue-329 version
```
app_1  | [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
app_1  | [s6-init] ensuring user provided files have correct perms...exited 0.
app_1  | [fix-attrs.d] applying ownership & permissions fixes...
app_1  | [fix-attrs.d] 01-fix-index.php: applying... 
app_1  | [fix-attrs.d] 01-fix-index.php: exited 0.
app_1  | [fix-attrs.d] 02-fix-www-catalog: applying... 
app_1  | [fix-attrs.d] 02-fix-www-catalog: exited 0.
app_1  | [fix-attrs.d] done.
app_1  | [cont-init.d] executing container initialization scripts...
app_1  | [cont-init.d] done.
app_1  | [services.d] starting services
app_1  | [services.d] done.
```

file `01-fix-index.php`
```
/var/www/html/index.php true www-data 0600 0700
```
file `02-fix-www-catalog`
```
/var/www/html true www-data:www-data 0644 0755
```

But when have bad file (example 01) and use variable `S6_BEHAVIOUR_IF_STAGE2_FAILS=2` execution continues
```
app_1  | [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
app_1  | [s6-init] ensuring user provided files have correct perms...exited 0.
app_1  | [fix-attrs.d] applying ownership & permissions fixes...
app_1  | [fix-attrs.d] 01-fix-index.php: applying... 
app_1  | s6-envuidgid: fatal: unknown user: www-data2
app_1  | [fix-attrs.d] 01-fix-index.php: exited 1.
app_1  | [fix-attrs.d] 02-fix-www-catalog: applying... 
app_1  | [fix-attrs.d] 02-fix-www-catalog: exited 0.
app_1  | [fix-attrs.d] done.
app_1  | [cont-init.d] executing container initialization scripts...
app_1  | [cont-init.d] done.
app_1  | [services.d] starting services
app_1  | [services.d] done.
```

**Comment by skarnet** [comment] 2022-01-20 10:37
Version 3.0.0.0 of s6-overlay is out, which should hopefully fix all these outstanding issues.
Please note that `fix-attrs` is deprecated; it's difficult to make work with `USER` containers, and a much better policy is to set appropriate ownership and permissions from outside the container, at the time when your filesystems are mounted or in your Dockerfile. It is still supported for now, though; I hope the new version of s6-overlay will work for you.
Closing this; please reopen if not fixed.

**Closed by skarnet** 2022-01-20 10:37 UTC
