### ISSUE TITLE
Docker does not cache: ADD https://github.com/.../s6-overlay-0.1.0-linux-amd64.tar.gz

### ISSUE THREAD

**Issue by dreamcat4** [just-containers/s6-overlay#4] opened 2015-03-02 13:07 UTC
So our ADD layer in `docker build`:

```dockerfile
ADD https://github.com/glerchundi/container-s6-overlay-builder/releases/download/v0.1.0/s6-overlay-0.1.0-linux-amd64.tar.gz /s6-overlay.tar.gz
```

Does not cache. According to the `Dockerfile` documentation on `ADD` command, it should check the `mtime` and not re-download the same file:

https://docs.docker.com/reference/builder/#add

Perhaps it is because the way github releases URL does behind redirects (i tihnk i saw to s3), and this is hiding to docker the real tarball file. And it cannot check the `mtime`.

I have not found yet such docker issue in `docker/docker` about it. Still looking.

**Comment by dreamcat4** [comment] 2015-03-04 10:58
OK. When I try the file from local Apache server, unfortunately it does not cache either. But I have found 2 docker tickets which might help in regards to caching:

https://github.com/docker/docker/issues/7748

https://github.com/docker/docker/issues/3050

Aparrently, docker was modified to set the `mtime` from the HTTP `last-modified` header.

**Comment by glerchundi** [comment] 2015-03-04 16:10
Thanks for your time looking related issues.

**Comment by duglin** [comment] 2015-03-04 17:20
@dreamcat4 can you write-up a small testcase to show this?  I can't reproduce it.

**Comment by dreamcat4** [comment] 2015-03-13 10:46
We have clarified to @duglin and relevant official docker people about the missing functionality of `ADD`. They are progressing the issue in due course which must be solved over there first. This issue can be closed right now. Because there seems no way we can get around docker not caching remote tarballs ATM.

If might be hosting our tarball somewhere else other than Github releases. It could mean a better control over the HTTP last-modified header, to be recognised by Docker... But docker is so bad right now at that stuff. Probably not worth all the hassle / other drawbacks.

They will eventually fix / improve the `ADD` command officially, and include the missing functionality with `ADD --flags`. Not just for the caching. But also so that `ADD` will auto un-tar remote tarball too. Those improvement will be quite desirable.

No code changes to action here on the s6-overlay...

**Comment by glerchundi** [comment] 2015-03-13 16:43
Thanks @dreamcat4, I'm going to keep it open just as a reminder :smile:

**Comment by glerchundi** [comment] 2015-08-25 08:41
Closing this due to: https://github.com/docker/docker/blob/master/ROADMAP.md#22-dockerfile-syntax.

**Closed by glerchundi** 2015-08-25 08:41 UTC
