### ISSUE TITLE
Long container stop time

### ISSUE THREAD

**Issue by NewbiZ** [just-containers/s6-overlay#534] opened 2023-06-06 05:46 UTC
When installing s6-overlay in a fresh new container, there is an incurred stop time that seem unavoidable through current configuration environment variables.

Let's showcase what I mean through a simple example.

First, with a container that does not have s6-overlay:

    $ cat Dockerfile
    FROM ubuntu:22.04
    
    $ docker build -q .
    sha256:48e95f7a95ec891a9449b72cdba3c04e87e9d42445e13047cac75d964085d277
    
    $ time docker run --rm 48e95f7a95ec891a9449b72cdba3c04e87e9d42445e13047cac75d964085d277 whoami
    root
    
    real	0m0,465s
    user	0m0,045s
    sys	0m0,011s

Then with the very same container after a fresh install of s6-overlay 3.1.5.0:

    $ cat Dockerfile
    FROM ubuntu:22.04
    
    RUN DEBIAN_FRONTEND=noninteractive apt-get update && apt-get install xz-utils
    ARG S6_OVERLAY_VERSION=3.1.5.0
    ADD https://github.com/just-containers/s6-overlay/releases/download/v${S6_OVERLAY_VERSION}/s6-overlay-noarch.tar.xz /tmp
    RUN tar -C / -Jxpf /tmp/s6-overlay-noarch.tar.xz
    ADD https://github.com/just-containers/s6-overlay/releases/download/v${S6_OVERLAY_VERSION}/s6-overlay-x86_64.tar.xz /tmp
    RUN tar -C / -Jxpf /tmp/s6-overlay-x86_64.tar.xz
    
    ENTRYPOINT ["/init"]

    $ docker build -q .
    sha256:9b1aed49172c3b0ccf1be50bc1a9d1a708a4341839501ec86def1255ddd3979a

    $ time docker run --rm 9b1aed49172c3b0ccf1be50bc1a9d1a708a4341839501ec86def1255ddd3979a whoami
    s6-rc: info: service s6rc-oneshot-runner: starting
    s6-rc: info: service s6rc-oneshot-runner successfully started
    s6-rc: info: service fix-attrs: starting
    s6-rc: info: service fix-attrs successfully started
    s6-rc: info: service legacy-cont-init: starting
    s6-rc: info: service legacy-cont-init successfully started
    s6-rc: info: service legacy-services: starting
    s6-rc: info: service legacy-services successfully started
    root
    s6-rc: info: service legacy-services: stopping
    s6-rc: info: service legacy-services successfully stopped
    s6-rc: info: service legacy-cont-init: stopping
    s6-rc: info: service legacy-cont-init successfully stopped
    s6-rc: info: service fix-attrs: stopping
    s6-rc: info: service fix-attrs successfully stopped
    s6-rc: info: service s6rc-oneshot-runner: stopping
    s6-rc: info: service s6rc-oneshot-runner successfully stopped

    real	0m4,535s
    user	0m0,023s
    sys	0m0,030s

Somehow, somewhere, s6-overlay takes an additional 4s at container shutdown. I cannot pinpoint exactly what is causing this. I tried setting pretty much all the configuration variables to 0 with no effect (`S6_KILL_FINISH_MAXTIME`, `S6_SERVICES_GRACETIME`, `S6_KILL_GRACETIME`, etc)

Increasing verbosity does not help either, since the 4s "wait" time happens after the last line of log at any verbosity level. 

    $ time docker run --rm --env S6_VERBOSITY=5 9b1aed49172c3b0ccf1be50bc1a9d1a708a4341839501ec86def1255ddd3979a whoami
    s6-rc-compile: tracing: from s6-rc-compile internals: adding identifier s6rc-oneshot-runner of type longrun
    s6-rc-compile: tracing: from s6-rc-compile internals: adding identifier s6rc-fdholder of type longrun
    s6-rc-compile: info: parsing /etc/s6-overlay/s6-rc.d/user
    s6-rc-compile: info: user has type bundle
    s6-rc-compile: tracing: from /etc/s6-overlay/s6-rc.d: adding identifier user of type bundle
    s6-rc-compile: info: parsing /etc/s6-overlay/s6-rc.d/user2
    s6-rc-compile: info: user2 has type bundle
    s6-rc-compile: tracing: from /etc/s6-overlay/s6-rc.d: adding identifier user2 of type bundle
    s6-rc-compile: info: parsing /package/admin/s6-overlay-3.1.5.0/etc/s6-rc/sources/base
    s6-rc-compile: info: base has type bundle
    s6-rc-compile: tracing: from /package/admin/s6-overlay-3.1.5.0/etc/s6-rc/sources: adding identifier base of type bundle
    s6-rc-compile: tracing: from base: adding identifier legacy-cont-init of type unknown
    s6-rc-compile: tracing: from base: adding identifier fix-attrs of type unknown
    s6-rc-compile: info: parsing /package/admin/s6-overlay-3.1.5.0/etc/s6-rc/sources/fix-attrs
    s6-rc-compile: info: fix-attrs has type oneshot
    s6-rc-compile: tracing: from /package/admin/s6-overlay-3.1.5.0/etc/s6-rc/sources: adding identifier fix-attrs of type oneshot
    s6-rc-compile: tracing: previously encountered identifier fix-attrs now has type oneshot
    s6-rc-compile: tracing: dependency from fix-attrs to s6rc-oneshot-runner (0)
    s6-rc-compile: info: parsing /package/admin/s6-overlay-3.1.5.0/etc/s6-rc/sources/legacy-cont-init
    s6-rc-compile: info: legacy-cont-init has type oneshot
    s6-rc-compile: tracing: from /package/admin/s6-overlay-3.1.5.0/etc/s6-rc/sources: adding identifier legacy-cont-init of type oneshot
    s6-rc-compile: tracing: previously encountered identifier legacy-cont-init now has type oneshot
    s6-rc-compile: tracing: from legacy-cont-init: adding identifier fix-attrs of type unknown
    s6-rc-compile: tracing: identifier fix-attrs was already declared with type oneshot
    s6-rc-compile: tracing: dependency from legacy-cont-init to fix-attrs (67)
    s6-rc-compile: tracing: dependency from legacy-cont-init to s6rc-oneshot-runner (0)
    s6-rc-compile: info: parsing /package/admin/s6-overlay-3.1.5.0/etc/s6-rc/sources/legacy-services
    s6-rc-compile: info: legacy-services has type oneshot
    s6-rc-compile: tracing: from /package/admin/s6-overlay-3.1.5.0/etc/s6-rc/sources: adding identifier legacy-services of type oneshot
    s6-rc-compile: tracing: from legacy-services: adding identifier user of type unknown
    s6-rc-compile: tracing: identifier user was already declared with type bundle
    s6-rc-compile: tracing: from legacy-services: adding identifier base of type unknown
    s6-rc-compile: tracing: identifier base was already declared with type bundle
    s6-rc-compile: tracing: dependency from legacy-services to user (34)
    s6-rc-compile: tracing: dependency from legacy-services to base (45)
    s6-rc-compile: tracing: dependency from legacy-services to s6rc-oneshot-runner (0)
    s6-rc-compile: info: parsing /package/admin/s6-overlay-3.1.5.0/etc/s6-rc/sources/top
    s6-rc-compile: info: top has type bundle
    s6-rc-compile: tracing: from /package/admin/s6-overlay-3.1.5.0/etc/s6-rc/sources: adding identifier top of type bundle
    s6-rc-compile: tracing: from top: adding identifier user of type unknown
    s6-rc-compile: tracing: identifier user was already declared with type bundle
    s6-rc-compile: tracing: from top: adding identifier user2 of type unknown
    s6-rc-compile: tracing: identifier user2 was already declared with type bundle
    s6-rc-compile: tracing: from top: adding identifier base of type unknown
    s6-rc-compile: tracing: identifier base was already declared with type bundle
    s6-rc-compile: tracing: from top: adding identifier legacy-services of type unknown
    s6-rc-compile: tracing: identifier legacy-services was already declared with type oneshot
    s6-rc-compile: info: making bundles for pipelines
    s6-rc-compile: info: resolving bundle names
    s6-rc-compile: info: converting bundle array
    s6-rc-compile: info: resolving service names
    s6-rc-compile: tracing: fix-attrs depends on longrun s6rc-oneshot-runner (0)
    s6-rc-compile: tracing: legacy-cont-init depends on oneshot fix-attrs (2)
    s6-rc-compile: tracing: legacy-cont-init depends on longrun s6rc-oneshot-runner (0)
    s6-rc-compile: tracing: legacy-services depends on bundle user
    s6-rc-compile: tracing: legacy-services depends on bundle base
    s6-rc-compile: tracing: legacy-services depends on longrun s6rc-oneshot-runner (0)
    s6-rc-compile: info: converting service dependency array
    s6-rc-compile: info: checking database correctness
    s6-rc-compile: info: writing compiled information to /run/s6/db
    s6-rc-compile: info: writing /run/s6/db/n
    s6-rc-compile: info: writing /run/s6/db/resolve.cdb
    s6-rc-compile: info: writing /run/s6/db/db
    s6-rc-compile: info: writing /run/s6/db/servicedirs
    s6-rc: info: bringing selected services up
    s6-rc: info: service s6rc-oneshot-runner: starting
    s6-rc: info: service s6rc-oneshot-runner successfully started
    s6-rc: info: service fix-attrs: starting
    s6-ipcclient: info: s6-ipcclient: connected to /run/s6-rc/servicedirs/s6rc-oneshot-runner/s
    s6-rc: info: service fix-attrs successfully started
    s6-rc: info: service legacy-cont-init: starting
    s6-ipcclient: info: s6-ipcclient: connected to /run/s6-rc/servicedirs/s6rc-oneshot-runner/s
    s6-rc: info: service legacy-cont-init successfully started
    s6-rc: info: service legacy-services: starting
    s6-ipcclient: info: s6-ipcclient: connected to /run/s6-rc/servicedirs/s6rc-oneshot-runner/s
    s6-rc: info: service legacy-services successfully started
    root
    s6-rc: info: bringing selected services down
    s6-rc: info: service legacy-services: stopping
    s6-ipcclient: info: s6-ipcclient: connected to /run/s6-rc/servicedirs/s6rc-oneshot-runner/s
    s6-rc: info: service legacy-services successfully stopped
    s6-rc: info: service legacy-cont-init: stopping
    s6-ipcclient: info: s6-ipcclient: connected to /run/s6-rc/servicedirs/s6rc-oneshot-runner/s
    s6-rc: info: service legacy-cont-init successfully stopped
    s6-rc: info: service fix-attrs: stopping
    s6-ipcclient: info: s6-ipcclient: connected to /run/s6-rc/servicedirs/s6rc-oneshot-runner/s
    s6-rc: info: service fix-attrs successfully stopped
    s6-rc: info: service s6rc-oneshot-runner: stopping
    s6-rc: info: service s6rc-oneshot-runner successfully stopped
                 <----------------------------- 4s wait time here 
    real	0m4,653s
    user	0m0,037s
    sys	0m0,022s

**Comment by skarnet** [comment] 2023-06-06 10:15
This definitely sounds like a `S6_KILL_GRACETIME` issue. Is the waiting time the same when you define `S6_KILL_GRACETIME` to `0`? and to `1`?

**Comment by NewbiZ** [comment] 2023-06-06 12:55
Interestingly, `S6_KILL_GRACETIME` seem to have an influence as long as it's non-zero.

    $ time docker run --env S6_KILL_GRACETIME=0 --env S6_VERBOSITY=0 --rm 9b1aed49172c3b0ccf1be50bc1a9d1a708a4341839501ec86def1255ddd3979a :
    
    real	0m4,555s
    user	0m0,025s
    sys	0m0,015s
.

    $ time docker run --env S6_KILL_GRACETIME=1 --env S6_VERBOSITY=0 --rm 9b1aed49172c3b0ccf1be50bc1a9d1a708a4341839501ec86def1255ddd3979a :
    
    real	0m1,487s
    user	0m0,027s
    sys	0m0,017s
.

    $ time docker run --env S6_KILL_GRACETIME=2 --env S6_VERBOSITY=0 --rm 9b1aed49172c3b0ccf1be50bc1a9d1a708a4341839501ec86def1255ddd3979a :
    
    real	0m1,495s
    user	0m0,022s
    sys	0m0,027s
.

    $ time docker run --env S6_KILL_GRACETIME=5 --env S6_VERBOSITY=0 --rm 9b1aed49172c3b0ccf1be50bc1a9d1a708a4341839501ec86def1255ddd3979a :
    
    real	0m1,548s
    user	0m0,012s
    sys	0m0,021s
.

    $ time docker run --env S6_KILL_GRACETIME=1000 --env S6_VERBOSITY=0 --rm 9b1aed49172c3b0ccf1be50bc1a9d1a708a4341839501ec86def1255ddd3979a :
    
    real	0m2,477s
    user	0m0,025s
    sys	0m0,017s
.

    $ time docker run --env S6_KILL_GRACETIME=2000 --env S6_VERBOSITY=0 --rm 9b1aed49172c3b0ccf1be50bc1a9d1a708a4341839501ec86def1255ddd3979a :
    
    real	0m3,491s
    user	0m0,011s
    sys	0m0,023s
.

    $ time docker run --env S6_KILL_GRACETIME=3000 --env S6_VERBOSITY=0 --rm 9b1aed49172c3b0ccf1be50bc1a9d1a708a4341839501ec86def1255ddd3979a :
    
    real	0m4,579s
    user	0m0,043s
    sys	0m0,026s

**Comment by skarnet** [comment] 2023-06-06 18:22
OK, I found the extra second. It's not an immediate fix, but it will be fixed in the next numbered release of s6-overlay, at the same time `S6_KILL_GRACETIME=0` is fixed.

Until then, please use `S6_KILL_GRACETIME=1` and sorry for the one second and one millisecond of extra delay. ;-)

**Closed by skarnet** 2023-06-06 18:22 UTC

**Comment by davidkaufman** [comment] 2023-06-08 05:49
> You are the best :-)

+1 

Life is short.  Every milliseconds matters :-)

**Comment by skarnet** [comment] 2023-06-21 01:52
I've finally managed to get a fix I'm happy with; the new release should appear some time next month, at the same time I release new versions of the whole skarnet.org stack.

A heads-up though: you will *still* feel like it takes longer than necessary to run `docker run foobar whoami`. However, it will take the *same time*, more or less, to run `docker run foobar sleep 1 whoami`.

The explanation is that the supervisor, by design, always waits a minimum of 1 second between two launches of the same service (this prevents cascading failure in case of a service error); and the shutdown sequence involves killing everything and restarting one process to finish the sequence, so if less than one second has elapsed since the container was started, the shutdown sequence will wait until the full second has passed before completing. In the huge majority of cases, though, containers run for more than one second, so the shutdown will be as instantaneous as possible.
