### ISSUE TITLE
If i hava a script to excute before /init, how should I do?

### ISSUE THREAD

**Issue by situjianxiong** [just-containers/s6-overlay#505] opened 2022-12-13 10:44 UTC
If i hava a script to excute before /init, how should I do?

**Comment by skarnet** [comment] 2022-12-13 16:09
That's the neat part: you don't.

If you're using s6-overlay, `/init` is always the first process running in your container. By definition. If you're not running `/init` as the first process, then you're not running s6-overlay.

The good news is that you probably don't need to run your script before `/init`. There are a lot of moments where it will likely run just as well. Normally, running it as a one-shot service before all the other services should work. If that won't work for you because you need to do dirty things with the container before you launch the services, then s6-overlay v3 provides you, as documented in the [README file](https://github.com/just-containers/s6-overlay/blob/master/README.md), with a `S6_STAGE2_HOOK` variable: set this variable to the name of your script, and it will be run as early as possible. You can't get any earlier than that, and that's on purpose.

In order to help you further, I would need the details on what exactly you're attempting to do. But it seems like you're currently using s6-overlay v2, so it will have to wait until you upgrade.

Good luck.

**Comment by situjianxiong** [comment] 2022-12-14 01:41
that is something different between s6-overlay v2 and v3: v3 have to be started as the first process; I am trying to use v3, but there are some prepare work to do before the service start, such as config which need the modify depend on env,so how can i do?thanks!

**Comment by skarnet** [comment] 2022-12-14 05:18
v2 *also* needed to be started as the first process. It *appeared* to work otherwise, but it didn't; chances are your setup was subtly broken. v3 is more upfront, by refusing to run altogether if it's not pid 1.

It is intentional that service dependencies are static. This ensures reproducibility of the container boot. You are not supposed to dynamically change service dependencies.

That said, as I mentioned above, if you really need to do this, the `S6_STAGE2_HOOK` environment variable is meant for you.

**Comment by skarnet** [comment] 2023-01-18 22:44
Closing this.

**Closed by skarnet** 2023-01-18 22:44 UTC

**Comment by viriatusX** [comment] 2023-03-30 23:13
<img width="978" alt="Captura de pantalla 2023-03-31 a las 1 09 57" src="https://user-images.githubusercontent.com/64467637/228984637-b7deae8e-6c2a-4c92-bf53-182adb2a38cb.png">
<img width="986" alt="Captura de pantalla 2023-03-31 a las 1 09 26" src="https://user-images.githubusercontent.com/64467637/228984652-e53a7c77-4e0e-486d-81d5-6a98afc6c633.png">

Hello, I don't know if you can help me. I have a Nginx Docker installed that has updated S6 modules and I can't run a .sh when starting the Docker with ENTRYPOINT. In the previous version, the PID 1 was the .sh, and in the new version it is the s6-svscan service.
Since the last version, when starting Docker I get the error s6-overlay-suexec: fatal: can only run as pid 1.
Is there any way to fix it?
Thank you very much

**Comment by skarnet** [comment] 2023-03-31 00:04
s6-overlay has never supported not running s6-svscan as pid 1. In previous versions, it did not yield an error, but the fact that it worked was purely accidental and chances are there were things in your setup that were subtly broken. s6-overlay v3 avoids this by failing outright when it's not run as pid 1.

I recommend you look into your container's organization and your init's shell script to make it possible to run s6-overlay.
